// os_in_browser/src/App.tsx
import { createSignal, onCleanup } from "solid-js";
import {
  ProcessDirectoryProvider,
  useProcess,
} from "./context/processDirectory";
import { FileSystemProvider } from "./context/windowFileSystem";
import Main from "./main";
import "./style/desktop.scss";
import "./style/global.scss";
import "./style/variables.scss";
import "./style/window.scss";
import "./style/finder.scss";
import "./style/onClickDragBox.scss";

const App = () => {
  return (
    <FileSystemProvider>
      <ProcessDirectoryProvider>
        <Main />
      </ProcessDirectoryProvider>
    </FileSystemProvider>
  );
};

export default App;

// my-solid-project/src/App.tsx
import { ProcessDirectoryProvider } from "./context/processDirectory";
import { FileSystemProvider } from "./context/windowFileSystem";
import Main from "./app/Desktop";
import "./style/desktop.scss";
import "./style/global.scss";
import "./style/variables.scss";
import "./style/window.scss";
import "./style/finder.scss";
import "./style/loader.scss";
import "./style/dragDrop.scss";

//customMenu
import "./style/customMenu.scss";

//circularMenu
import "./style/circularMenu.scss";
import { FilesProvider } from "./context/FilesContext";

const App = () => {
  return (
    <FileSystemProvider>
      <FilesProvider>
        <ProcessDirectoryProvider>
          <Main />
        </ProcessDirectoryProvider>
      </FilesProvider>
    </FileSystemProvider>
  );
};

export default App;
